import React, { useState } from 'react';
import { X, Coins, Backpack, Gift } from 'lucide-react';

export default function CourierProfileModal({ isOpen, onClose, courier, stats, onGivePoints }) {
  const [pointsToGive, setPointsToGive] = useState("");
  const [giveReason, setGiveReason] = useState("");
  if (!isOpen || !courier || !stats) return null;
  return (
    <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/60 p-4 animate-in fade-in zoom-in duration-200">
      <div className="w-full max-w-sm bg-white rounded-3xl p-6 shadow-2xl relative overflow-hidden flex flex-col max-h-[90vh] overflow-y-auto custom-scrollbar">
        <button onClick={onClose} className="absolute top-4 right-4 text-slate-400 hover:text-slate-600 z-10 bg-white/50 p-1 rounded-full"><X size={24} /></button>
        <div className="absolute top-0 left-0 w-full h-24 bg-gradient-to-r from-indigo-500 to-purple-600 shrink-0"></div>
        <div className="relative pt-8 text-center mb-6 shrink-0"><div className="w-24 h-24 mx-auto rounded-full border-4 border-white shadow-lg overflow-hidden bg-white mb-3 relative group"><img src={courier.photoUrl || `https://api.dicebear.com/7.x/avataaars/svg?seed=${courier.name}`} className="w-full h-full object-cover" alt={courier.name} /><div className={`absolute bottom-0 right-0 w-6 h-6 rounded-full flex items-center justify-center text-xs text-white border-2 border-white ${stats.level.color}`}>{stats.level.emoji}</div></div><h2 className="text-xl font-bold text-slate-900 flex items-center justify-center gap-1">{courier.name} <span className="text-xs text-slate-400 font-normal">학생 기사</span></h2><p className="text-sm text-slate-500 mt-1 px-4 line-clamp-2">"{String(courier.description || "안전하게 배송하겠습니다!")}"</p><div className="mt-2 flex justify-center items-center gap-1 text-indigo-600 font-bold bg-indigo-50 py-1 px-3 rounded-full mx-auto w-fit"><Coins size={14} className="fill-indigo-600" /> {courier.points || 0} P</div></div>
        <div className="bg-slate-50 rounded-2xl p-5 mb-4 border border-slate-100 shrink-0"><div className="flex justify-between items-end mb-3"><div className="flex items-center gap-2"><span className="text-2xl">{stats.level.emoji}</span><div><p className="text-xs text-slate-400 font-bold">현재 레벨</p><p className="text-sm font-black text-slate-800">{stats.level.name}</p></div></div><div className="text-right"><p className="text-xs text-slate-400">총 배송 완료</p><p className="text-lg font-black text-indigo-600">{stats.deliveredCount}건</p></div></div><div className="w-full bg-slate-200 rounded-full h-2.5 overflow-hidden"><div className={`h-full ${stats.level.color} transition-all duration-500`} style={{ width: `${stats.progress}%` }}></div></div><p className="text-[10px] text-slate-400 text-right mt-1">다음 레벨까지 {stats.nextLevel ? stats.nextLevel.min - stats.deliveredCount : 0}건 남음</p></div>
        <div className="grid grid-cols-2 gap-3 mb-4 shrink-0"><div className="bg-white border border-slate-100 rounded-2xl p-4 flex flex-col items-center justify-center shadow-sm"><span className="text-2xl mb-1">⭐</span><p className="text-xs text-slate-400 font-bold">평균 평점</p><p className="text-lg font-black text-slate-800">{stats.avgRating.toFixed(1)} <span className="text-xs text-slate-300">/ 5.0</span></p></div><div className="bg-white border border-slate-100 rounded-2xl p-4 flex flex-col items-center justify-center shadow-sm"><span className="text-2xl mb-1">🏆</span><p className="text-xs text-slate-400 font-bold">획득 뱃지</p><p className="text-lg font-black text-slate-800">{stats.badges.length}개</p></div></div>
        <div className="bg-white border border-slate-200 rounded-2xl p-4 mb-4 shadow-sm shrink-0"><h4 className="font-bold text-slate-800 text-sm mb-3 flex items-center gap-2"><Backpack size={16} className="text-indigo-600" /> 로켓 배낭 <span className="text-slate-400 font-normal text-xs">({courier.inventory?.length || 0})</span></h4>{!courier.inventory || courier.inventory.length === 0 ? (<div className="text-center py-6 text-slate-400 text-xs bg-slate-50 rounded-xl border border-slate-100 border-dashed">보유한 아이템이 없습니다.</div>) : (<div className="grid grid-cols-4 gap-2">{[...courier.inventory].sort((a, b) => (a.isUsed === b.isUsed ? 0 : a.isUsed ? 1 : -1)).map((item, idx) => (<div key={idx} className={`relative flex flex-col items-center p-2 rounded-xl border transition-all ${item.isUsed ? 'bg-slate-100 border-slate-100 opacity-50' : 'bg-indigo-50 border-indigo-100'}`}><div className="text-xl mb-1">{item.icon}</div><span className="text-[9px] text-center font-medium leading-tight line-clamp-2 break-all text-slate-600">{item.name}</span>{item.isUsed && (<div className="absolute inset-0 flex items-center justify-center bg-white/40 rounded-xl backdrop-blur-[1px]"><span className="text-[8px] font-bold bg-slate-600 text-white px-1.5 py-0.5 rounded-full">USED</span></div>)}</div>))}</div>)}</div>
        {onGivePoints && (<div className="bg-white border border-amber-200 rounded-2xl p-4 mb-4 shadow-sm shrink-0"><h4 className="font-bold text-amber-600 text-sm mb-2 flex items-center gap-1"><Gift size={14} /> 특별 포인트 지급</h4><div className="flex gap-2 mb-2"><input type="number" value={pointsToGive} onChange={(e) => setPointsToGive(e.target.value)} placeholder="점수" className="w-20 border border-slate-200 rounded-lg px-2 py-1 text-sm outline-none focus:border-amber-400" /><input type="text" value={giveReason} onChange={(e) => setGiveReason(e.target.value)} placeholder="사유 (예: 선행)" className="flex-1 border border-slate-200 rounded-lg px-2 py-1 text-sm outline-none focus:border-amber-400" /></div><button onClick={() => { if (pointsToGive && giveReason) { onGivePoints(courier.id, parseInt(pointsToGive), giveReason); setPointsToGive(""); setGiveReason(""); } }} className="w-full bg-amber-500 hover:bg-amber-600 text-white font-bold py-2 rounded-lg text-xs shadow-md transition-colors">지급하기</button></div>)}
        <div className="bg-indigo-50 rounded-xl p-3 text-center shrink-0"><p className="text-xs text-indigo-400 font-bold mb-1">배송 가능 시간</p><div className="flex flex-wrap justify-center gap-1">{courier.availableSlots.map((slot) => (<span key={slot} className="bg-white text-indigo-600 px-2 py-0.5 rounded text-[10px] font-bold border border-indigo-100">{slot}</span>))}</div></div>
      </div>
    </div>
  );
}
