export const LOGIN_STORAGE_KEY = "rocket_talk_login";
export const TIME_SLOTS = ["아침시간", "1교시", "2교시", "3교시", "4교시", "점심시간", "5교시", "6교시", "7교시", "방과후"];

export const LEVEL_THRESHOLDS = [
    { name: "수습 기사", min: 0, color: "bg-slate-500", emoji: "🌱" },
    { name: "일반 기사", min: 5, color: "bg-emerald-500", emoji: "🚲" },
    { name: "베테랑 기사", min: 15, color: "bg-indigo-500", emoji: "🛵" },
    { name: "전설의 기사", min: 30, color: "bg-amber-500", emoji: "👑" }
];

export const DEFAULT_SHOP_ITEMS = [
    { id: 1, name: "급식 우선권 (1회)", price: 50, icon: "🍚", desc: "줄 서지 않고 먼저 먹을 수 있어요!" },
    { id: 2, name: "도서관 대출 +1권", price: 30, icon: "📚", desc: "일주일간 책을 한 권 더 빌려요." },
    { id: 3, name: "체육관 점심 사용권", price: 100, icon: "🏀", desc: "점심시간 체육관 프리패스!" },
    { id: 4, name: "선생님과 폴라로이드", price: 150, icon: "📸", desc: "담임 선생님과 추억 남기기" },
    { id: 5, name: "매점 1,000원 쿠폰", price: 200, icon: "🌭", desc: "맛있는 간식을 사먹어요." }
];

export const initialStaff = [
    { id: "s1", name: "류현진", role: "생활안전부장(영어)", location: "본관 1층/생활안전부", isOnline: false },
    { id: "s2", name: "문은지", role: "창의인성부장(미술)", location: "본관 1층", isOnline: false },
    { id: "s3", name: "김민정", role: "창의인성부장(역사)", location: "본관 1층", isOnline: false },
    { id: "s4", name: "유미란", role: "교무기획부장(국어)", location: "본관 1층", isOnline: false },
    { id: "s5", name: "정연수", role: "교육연구부장(사회)", location: "본관 1층", isOnline: false },
    { id: "s6", name: "장영주", role: "교감", location: "본관 1층/교감실", isOnline: false },
    { id: "s7", name: "이병일", role: "교장", location: "본관 1층/교장실", isOnline: false },
    { id: "s9", name: "김효숙", role: "기획1(한문)", location: "본관 1층/생활안전부", isOnline: false },
    { id: "s10", name: "강옥주", role: "영어강사", location: "본관 1층", isOnline: false },
    { id: "s13", name: "남기원", role: "배움터지킴이", location: "본관 1층", isOnline: false },
    { id: "s14", name: "정상일", role: "창의기획(수학)", location: "본관 1층", isOnline: false },
    { id: "s15", name: "민준형", role: "도덕강사", location: "본관 1층", isOnline: false },
    { id: "s18", name: "강인희", role: "교무기획/고사계(가정)", location: "본관 1층", isOnline: false },
    { id: "s19", name: "손우림", role: "고사계(국어)", location: "본관 1층", isOnline: false },
    { id: "s20", name: "이솜이", role: "교무실무사", location: "본관 1층", isOnline: false },
    { id: "s21", name: "이예지", role: "교무행정지원사", location: "본관 1층", isOnline: false },
    { id: "s4c", name: "조경애", role: "지역사회전문가", location: "본관 1층/ 행복나루터", isOnline: false },
    { id: "s27", name: "황정민", role: "보건실", location: "보건실", isOnline: false },
    { id: "s28", name: "박승배", role: "인쇄실", location: "인쇄실", isOnline: false },
    { id: "s29", name: "임윤오", role: "시설관리실", location: "시설관리실", isOnline: false },
    { id: "sa1", name: "김현숙", role: "행정실장", location: "행정실", isOnline: false },
    { id: "sa2", name: "심은희", role: "예산세출", location: "행정실", isOnline: false },
    { id: "sa3", name: "김은진", role: "급여", location: "행정실", isOnline: false },
    { id: "sa4", name: "박영미", role: "세입", location: "행정실", isOnline: false },
    { id: "sc1", name: "이호준", role: "체육보건부장(체육)", location: "꿈나래관", isOnline: false },
    { id: "sc2", name: "임수신", role: "기획 체육계 / 3-1반", location: "꿈나래관/3학년부", isOnline: false },
    { id: "sc3", name: "이충형", role: "체육계 / 2-2반", location: "꿈나래관/2학년부", isOnline: false },
    { id: "sc4", name: "임형남", role: "체육강사/스포츠클럽", location: "꿈나래관", isOnline: false },
    { id: "sc5", name: "유광희", role: "체육강사/스포츠클럽", location: "꿈나래관", isOnline: false },
    { id: "sc6", name: "박경모", role: "체육강사/스포츠클럽", location: "꿈나래관", isOnline: false },
    { id: "sc7", name: "문종윤", role: "체육강사/스포츠클럽", location: "꿈나래관", isOnline: false },
    { id: "sc8", name: "이홍은", role: "급식실", location: "급식실", isOnline: false },
    { id: "sb2", name: "안현주", role: "진로(진로진학부장)", location: "본관 2층", isOnline: false },
    { id: "sb3", name: "이홍규", role: "특수(과학정보부장)", location: "본관 2층/과학정보부", isOnline: false },
    { id: "sb5", name: "이지숙", role: "실무사(과학정보부)", location: "본관 2층/과학정보부", isOnline: false },
    { id: "s4d", name: "김은주", role: "전문상담", location: "본관 2층/위클래스", isOnline: false },
    { id: "s3a", name: "이재근", role: "3학년부장(수학) / 3-1반", location: "본관 2층/3학년부", isOnline: false },
    { id: "s3b", name: "석예지", role: "인문방과후 / 3-2반", location: "본관 2층/3학년부", isOnline: false },
    { id: "s3c", name: "임수신", role: "체육보건기획 / 3-1반", location: "본관 2층/3학년부", isOnline: false },
    { id: "s3d", name: "박소진", role: "진학2(음악) / 3-4반", location: "본관 2층/3학년부", isOnline: false },
    { id: "s3e", name: "오승연", role: "진학1(과학) / 3-6반", location: "본관 2층/3학년부", isOnline: false },
    { id: "s3f", name: "최유선", role: "생활안전부2(과학) / 3-3반", location: "본관 2층/3학년부", isOnline: false },
    { id: "s3g", name: "조은미", role: "3학년기획(국어) / 3-5반", location: "본관 2층/3학년부", isOnline: false },
    { id: "s3h", name: "하의수", role: "생활교육계(역사) / 3-7반", location: "본관 2층/3학년부", isOnline: false },
    { id: "s1a", name: "김선재", role: "1학년부장(기술)", location: "본관 4층", isOnline: false },
    { id: "s1b", name: "이정민", role: "1학년 기획(가정) / 1-2반", location: "본관 4층/1학년부", isOnline: false },
    { id: "s1c", name: "곽기성", role: "생활교육계(도덕) / 1-1반", location: "본관 4층/1학년부", isOnline: false },
    { id: "s1d", name: "김윤서", role: "창의체험계(국어) / 1-3반", location: "본관 4층/1학년부", isOnline: false },
    { id: "s1e", name: "마연주", role: "학교평가계(영어) / 1-4반", location: "본관 4층/1학년부", isOnline: false },
    { id: "s2g", name: "이송민", role: "장학(수학) / 1-5반", location: "본관 4층/1학년부", isOnline: false },
    { id: "s1g", name: "전소현", role: "전교생활계(음악) / 1-6반", location: "본관 4층/1학년부", isOnline: false },
    { id: "s1h", name: "허지영", role: "자유학기계(과학) / 1-7반", location: "본관 4층/1학년부", isOnline: false },
    { id: "s1i", name: "박진아", role: "정보계(정보) / 1-8반", location: "본관 4층/1학년부", isOnline: false },
    { id: "sb1", name: "이진하", role: "사서", location: "본관 3층/도서관", isOnline: false },
    { id: "s2a", name: "이선화", role: "2학년부장(도덕)", location: "본관 3층", isOnline: false },
    { id: "s2b", name: "박수민", role: "2학년 기획(미술) / 2-1반", location: "본관 3층/2학년부", isOnline: false },
    { id: "s2c", name: "최태은", role: "성적처리계(중국어) / 2-2반", location: "본관 3층/2학년부", isOnline: false },
    { id: "s2d", name: "문경주", role: "NEIS(국어) / 2-3반", location: "본관 3층/2학년부", isOnline: false },
    { id: "s2e", name: "정근목", role: "안전교육계(수학) / 2-4반", location: "본관 3층/2학년부", isOnline: false },
    { id: "s2f", name: "조연미", role: "연구기획(수학) / 2-5반", location: "본관 3층/2학년부", isOnline: false },
    { id: "s1f", name: "김지연", role: "방과후교과서계(영어) / 2-6반", location: "본관 3층/2학년부", isOnline: false },
    { id: "s2h", name: "김서연", role: "과학정보 기획(과학) / 2-7반", location: "본관 3층/2학년부", isOnline: false },
    { id: "s2i", name: "최원우", role: "생활교육계(체육) / 2-8반", location: "본관 3층/2학년부", isOnline: false },
    { id: "s4a", name: "김삼수", role: "상담복지부장(사회)", location: "본관 4층", isOnline: false },
    { id: "s4b", name: "권세진", role: "통합교육실2(4층)", location: "본관 4층", isOnline: false },
    { id: "s4g", name: "이윤진", role: "특수실무사(4층)", location: "본관 4층", isOnline: false },
    { id: "set1", name: "축구부", role: "팀", location: "별도 시설", isOnline: false },
    { id: "set2", name: "후문지킴이실", role: "시설", location: "본관 1층", isOnline: false }
];

export const STAFF_LOCATIONS = ["본관 1층", "본관 2층", "본관 3층", "본관 4층", "꿈나래관", "행정실", "보건실", "급식실", "인쇄실", "시설관리실", "별도 시설", "미정"];
